### ISSUE TITLE
[PE-D] Unable to unmark a todo in a project

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-1/tp#100]
After marking a todo, there is no command to unmark the todo if i would like to unmark it in case i accidentally marked it as done. 

expected to be able to unmark a todo

![image.png](https://raw.githubusercontent.com/limjierui/ped/main/files/b772ac2d-7ec8-492f-8c21-cd830f52d610.png)

![image.png](https://raw.githubusercontent.com/limjierui/ped/main/files/54cf7742-bcf7-4900-bd95-301fea95be74.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: limjierui/ped#5

**Comment by Nineves** [comment]
no new function will be added in ver 2.1
