### ISSUE TITLE
[PE-D] Lines are not straight in the Model class diagram.

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-1/tp#119]
![image.png](https://raw.githubusercontent.com/matheril/ped/main/files/c194b5b8-4535-4318-b9e0-d140f71eb64b.png)

Consider making these straight to improve readability.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: matheril/ped#16

**Comment by Nineves** [comment]
solved
