### ISSUE TITLE
[PE-D] Lack of pictures in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-1/tp#121]
There are no pictures to illustrate the examples in the UG. Visually it may not easy for all to understand.

For example,
![image.png](https://raw.githubusercontent.com/limjierui/ped/main/files/589829b3-a370-4a76-a590-99bd72ac49ee.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: limjierui/ped#11

**Comment by Nineves** [comment]
I don't think we need 'pictures' in UG? since we've already got example of usage and output
