### ISSUE TITLE
[PE-D] Developer Guide's table of contents is incomplete

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-1/tp#124]
![image.png](https://raw.githubusercontent.com/matheril/ped/main/files/fb012aa0-0936-4b4b-8959-caad9ab2843b.png)

It would be much easier to navigate the Developer Guide if individual commands like `Add a Project` were included in the table of contents.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: matheril/ped#18

**Comment by Nineves** [comment]
Solved the issue
